using System;
using System.Collections.Generic;

namespace UOX3DfnStudio;

public static class DfnTagRegistry
{
    public static readonly HashSet<string> GeneralKnownDfnTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "GET",
        "NAME",
        "NAME2",
        "ID",
        "TYPE",
        "SCRIPT",
        "COLOUR",
        "COLOR",
        "AMOUNT",
        "WEIGHT",
        "WEIGHTMAX",
        "VALUE",
        "MOVABLE",
        "DECAY",
        "NEWBIE",
        "GOOD",
        "RESTOCK",
        "LAYER",
        "DYE",
        "PILEABLE",
        "MAXITEMS",
        "MAXNPCS",
        "MAXTIME",
        "MINTIME",
        "CALL",
        "WORLD",
        "INSTANCEID",
        "X1",
        "Y1",
        "X2",
        "Y2",
        "MORE",
        "MORE0",
        "MOREX",
        "MOREY",
        "MOREZ",
        "MORE1",
        "MORE2",
        "MORE3",
        "MORE4",
        "MORE5",
        "MORE6",
        "MORE7",
        "MORE8",
        "MORE9",
        "HP",
        "STR",
        "DEX",
        "INT",
        "MANA",
        "STAMINA",
        "FAME",
        "KARMA",
        "ATT",
        "DEF",
        "ARMOR",
        "DAMAGE",
        "RACE",
        "TITLE",
        "SKIN",
        "HAIRCOLOR",
        "HAIRSTYLE",
        "BEARDCOLOR",
        "BEARDSTYLE",
        "NPCAI",
        "NPCWANDER",
        "FLAG",
        "SECTIONID",
        "NPC",
        "NPCLIST",
        "ITEM",
        "ITEMLIST",
        "PACKITEM",
        "EQUIPITEM",
        "COLORLIST",
        "LOOT",
        "LOOTLIST",
        "RESOURCE",
        "SKILL",
        "MINRANK",
        "MAXRANK",
        "ADDITEM",
        "MENU",
        "SUBMENU",
        "COOKING",
        "BLACKSMITHING",
        "TAILORING",
        "BOWCRAFT",
        "CARPENTRY",
        "TINKERING",
        "INSCRIPTION",
        "ALCHEMY",
        "SMITH",
        "RANK",
        "SOUND",
        "SFX",
        "ANIM",
        "RESIST",
        "MAGICRESISTANCE",
        "PARRYING",
        "SWORDSMANSHIP",
        "FENCING",
        "MACEFIGHTING",
        "TACTICS",
        "WRESTLING",
        "ARCHERY",
        "MAGERY",
        "MEDITATION",
        "EVALUATINGINTEL",
        "SPIRITSPEAK",
        "PROVOCATION",
        "MUSICIANSHIP",
        "PEACEMAKING",
        "DISCORDANCE",
        "TAMING",
        "ANIMALLORE",
        "VETERINARY",
        "HEALING",
        "ANATOMY",
        "MINING",
        "LUMBERJACKING",
        "HIDING",
        "STEALTH",
        "SNOOPING",
        "STEALING",
        "LOCKPICKING",
        "REMOVETRAP",
        "DETECTINGHIDDEN",
        "FORENSICS",
        "ITEMID",
        "ARMSLORE",
        "TASTEID",
        "FISHING",
        "CAMPING",
        "TRACKING",
        "HERDING",
        "BEGGING",
        "POISONING",
        "CARTOGRAPHY",
        "ENTICEMENT",
        "FOOD",
        "THIRST",
        "HUNGER",
        "SHOPITEM",
        "SELLLIST",
        "BUYLIST",
        "DESC",
        "DESCRIPTION",
        "CNAME",
        "TRIGGER",
        "TRIGGERSCRIPT",
        "VISIBLE",
        "INVUL",
        "CANTRAIN",
        "NOTRAIN"
    };

    public static readonly HashSet<string> CreatureKnownDfnTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "ANTIBLINK",
        "ANIMAL",
        "ANIM_ATTACK1",
        "ANIM_ATTACK2",
        "ANIM_ATTACK3",
        "ANIM_CASTAREA",
        "ANIM_CASTTARGET",
        "ANIM_CAST3",
        "FLIES",
        "HUMAN",
        "ICON",
        "MOVEMENT",
        "MOUNTID",
        "PACKANIMAL",
        "SOUND_IDLE",
        "SOUND_STARTATTACK",
        "SOUND_ATTACK",
        "SOUND_DEFEND",
        "SOUND_DIE"
    };

    public static readonly HashSet<string> CreateKnownDfnTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "MENU",
        "SUBMENU",
        "ITEM",
        "NAME",
        "ID",
        "COLOUR",
        "COLOR",
        "RESOURCE",
        "SKILL",
        "ADDITEM",
        "MINRANK",
        "MAXRANK",
        "SOUND",
        "DELAY",
        "SPELL"
    };

    public static readonly HashSet<string> NpcKnownDfnTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "ALCHEMY",
        "ANATOMY",
        "ANIMALLORE",
        "ARCHERY",
        "ARMSLORE",
        "AWAKE",
        "BACKPACK",
        "BEGGING",
        "BLACKSMITHING",
        "BOWCRAFT",
        "BUSHIDO",
        "CAMPING",
        "CARPENTRY",
        "CARTOGRAPHY",
        "CARVE",
        "CHIVALRY",
        "COLOR",
        "COLOUR",
        "COLORLIST",
        "COLOURLIST",
        "COLORMATCHHAIR",
        "COLOURMATCHHAIR",
        "COOKING",
        "CUSTOMINTTAG",
        "CUSTOMSTRINGTAG",
        "DAMAGE",
        "ATT",
        "DEF",
        "DEFBONUS",
        "DETECTINGHIDDEN",
        "DEX",
        "DIR",
        "DIRECTION",
        "ELEMENTRESIST",
        "ERBONUS",
        "EMOTECOLOUR",
        "EMOTECOLOR",
        "ENTICEMENT",
        "EQUIPITEM",
        "EVALUATINGINTEL",
        "FAME",
        "FENCING",
        "FISHING",
        "FLAG",
        "FLEEAT",
        "FLEEINGSPEED",
        "FLEEINGSPEEDMOUNTED",
        "FOCUS",
        "FOOD",
        "FORENSICS",
        "FX1",
        "FX2",
        "FY1",
        "FY2",
        "FZ1",
        "GET",
        "GETUO",
        "GETT2A",
        "GETTD",
        "GETUOR",
        "GETLBR",
        "GETAOS",
        "GETSE",
        "GETML",
        "GETSA",
        "GETHS",
        "GETTOL",
        "GOLD",
        "HAIRCOLOR",
        "HAIRCOLOUR",
        "HEALING",
        "HERDING",
        "HIDAMAGE",
        "HIDING",
        "HP",
        "HPMAX",
        "HEALTHREGENBONUS",
        "STAMINAREGENBONUS",
        "MANAREGENBONUS",
        "ID",
        "IMBUING",
        "INSCRIPTION",
        "INTELLIGENCE",
        "INT",
        "ITEMID",
        "KARMA",
        "LOCKPICKING",
        "LODAMAGE",
        "LOOT",
        "LUMBERJACKING",
        "MACEFIGHTING",
        "MAGERY",
        "MAGICRESISTANCE",
        "MANA",
        "MANAMAX",
        "MEDITATION",
        "MINING",
        "MUSICIANSHIP",
        "MYSTICISM",
        "NAME",
        "NAMELIST",
        "NECROMANCY",
        "NINJITSU",
        "NOTRAIN",
        "NPCAI",
        "NPCWANDER",
        "ORIGIN",
        "PACKITEM",
        "PARRYING",
        "PEACEMAKING",
        "POISONING",
        "POISONSTRENGTH",
        "PRIV",
        "PROVOCATION",
        "RACE",
        "REATTACKAT",
        "REMOVETRAP",
        "RSHOPITEM",
        "RUNNINGSPEED",
        "RUNNINGSPEEDMOUNTED",
        "RUNS",
        "SAYCOLOR",
        "SAYCOLOUR",
        "SCRIPT",
        "SECTIONID",
        "SELLITEM",
        "SHOPITEM",
        "SHOPKEEPER",
        "SHOPLIST",
        "SKILL",
        "SKIN",
        "SKINLIST",
        "SNOOPING",
        "SPADELAY",
        "SPATTACK",
        "SPELLWEAVING",
        "SPIRITSPEAK",
        "SPLIT",
        "SPLITCHANCE",
        "STAMINA",
        "STAMINAMAX",
        "STEALING",
        "STEALTH",
        "STRENGTH",
        "STR",
        "SWORDSMANSHIP",
        "TACTICS",
        "TAILORING",
        "TAMEDHUNGER",
        "TAMING",
        "TASTEID",
        "THROWING",
        "TINKERING",
        "TITLE",
        "TOPEACE",
        "TOPROV",
        "TOTAME",
        "TRACKING",
        "VETERINARY",
        "WALKINGSPEED",
        "WALKINGSPEEDMOUNTED",
        "WILLHUNGER",
        "WRESTLING"
    };

    public static readonly HashSet<string> ItemKnownDfnTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "AC",
        "ADDMENUITEM",
        "ARTIFACTRARITY",
        "AMMO",
        "AMMOFX",
        "AMOUNT",
        "ATT",
        "BASEWEIGHT",
        "COLD",
        "COLOR",
        "COLOUR",
        "COLORLIST",
        "COLOURLIST",
        "CORPSE",
        "CREATOR",
        "CUSTOMINTTAG",
        "CUSTOMSTRINGTAG",
        "DURABILITYHPBONUS",
        "DAMAGE",
        "DAMAGEABLE",
        "DAMAGEINCREASE",
        "DECAY",
        "DEF",
        "DEFBONUS",
        "DEFENSECHANCE",
        "DEX",
        "DEXADD",
        "DIR",
        "DISABLED",
        "DISPELLABLE",
        "DYE",
        "EVENT",
        "ELEMENTRESIST",
        "ERBONUS",
        "GET",
        "GETUO",
        "GETT2A",
        "GETTD",
        "GETUOR",
        "GETLBR",
        "GETAOS",
        "GETSE",
        "GETML",
        "GETSA",
        "GETHS",
        "GETTOL",
        "GUMPTYPE",
        "GLOW",
        "GLOWBC",
        "GLOWTYPE",
        "GOOD",
        "HEAT",
        "HEALTHLEECH",
        "HEALTHBONUS",
        "HIDAMAGE",
        "HITCHANCE",
        "HP",
        "HEALTHREGENBONUS",
        "STAMINAREGENBONUS",
        "MANAREGENBONUS",
        "ID",
        "INTADD",
        "INTELLIGENCE",
        "INTERVAL",
        "LAYER",
        "LIGHT",
        "LIGHTNING",
        "LODAMAGE",
        "LOOT",
        "LOWERSTATREQ",
        "LUCK",
        "MANALEECH",
        "MANABONUS",
        "MAXHP",
        "MAXITEMS",
        "MAXRANGE",
        "MAXUSES",
        "MORE",
        "MORE0",
        "MORE1",
        "MORE2",
        "MOREX",
        "MOREY",
        "MOREZ",
        "MOREXYZ",
        "MOVABLE",
        "NAME",
        "NAMELIST",
        "NAME2",
        "NEWBIE",
        "OFFSPELL",
        "ORIGIN",
        "PACKITEM",
        "PILEABLE",
        "POISONDAMAGE",
        "POISONED",
        "PRIV",
        "RACE",
        "RESISTFIRE",
        "RESISTCOLD",
        "RESISTLIGHTING",
        "RESISTPOISON",
        "RAIN",
        "RANK",
        "RESTOCK",
        "SCRIPT",
        "SECTIONID",
        "SK_MADE",
        "SNOW",
        "SPAWNOBJ",
        "SPAWNOBJLIST",
        "SPD",
        "SWINGSPEEDINCREASE",
        "STEALABLE",
        "STAMINALEECH",
        "STAMINABONUS",
        "SPELLS",
        "STRADD",
        "STRENGTH",
        "STR",
        "TYPE",
        "USESLEFT",
        "VALUE",
        "VISIBLE",
        "WEIGHT",
        "WEIGHTMAX",
        "WIPE"
    };

    public static readonly HashSet<string> RaceKnownDfnTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "ALLOWEQUIPLIST",
        "ALLSKILLSG",
        "ALLSKILLSL",
        "ARMORREST",
        "BANEQUIPLIST",
        "BEARDMIN",
        "BEARDMAX",
        "BLOODCOLOUR",
        "COLDAFFECT",
        "COLDLEVEL",
        "COLDDAMAGE",
        "COLDSECS",
        "DEXCAP",
        "GENDER",
        "HAIRMIN",
        "HAIRMAX",
        "HEATAFFECT",
        "HEATDAMAGE",
        "HEATLEVEL",
        "HEATSECS",
        "HPMOD",
        "HUNGER",
        "INTCAP",
        "LIGHTAFFECT",
        "LIGHTDAMAGE",
        "LIGHTLEVEL",
        "LIGHTSECS",
        "LIGHTNINGAFFECT",
        "LIGHTNINGDAMAGE",
        "LIGHTNINGCHANCE",
        "LANGUAGEMIN",
        "MAGICRESISTANCE",
        "MANAMOD",
        "MAXWEIGHTBONUS",
        "NAME",
        "NOBEARD",
        "NIGHTVIS",
        "PLAYERRACE",
        "POISONRESISTANCE",
        "PARENTRACE",
        "REQUIREBEARD",
        "RAINAFFECT",
        "RAINDAMAGE",
        "RAINSECS",
        "RACERELATION",
        "RACIALENEMY",
        "RACIALAID",
        "SKINMIN",
        "SKINMAX",
        "SNOWAFFECT",
        "SNOWDAMAGE",
        "SNOWSECS",
        "STAMMOD",
        "STORMAFFECT",
        "STORMDAMAGE",
        "STORMSECS",
        "STRCAP",
        "THIRST",
        "VISRANGE",
        "ALCHEMYG",
        "ALCHEMYL",
        "ANATOMYG",
        "ANATOMYL",
        "ANIMALLOREG",
        "ANIMALLOREL",
        "ARCHERYG",
        "ARCHERYL",
        "ARMSLOREG",
        "ARMSLOREL",
        "BEGGINGG",
        "BEGGINGL",
        "BLACKSMITHINGG",
        "BLACKSMITHINGL",
        "BOWCRAFTG",
        "BOWCRAFTL",
        "BUSHIDOG",
        "BUSHIDOL",
        "CAMPINGG",
        "CAMPINGL",
        "CARPENTRYG",
        "CARPENTRYL",
        "CARTOGRAPHYG",
        "CARTOGRAPHYL",
        "CHIVALRYG",
        "CHIVALRYL",
        "COOKINGG",
        "COOKINGL",
        "DETECTINGHIDDENG",
        "DETECTINGHIDDENL",
        "DISCORDANCEG",
        "DISCORDANCEL",
        "ENTICEMENTG",
        "ENTICEMENTL",
        "EVALUATINGINTELG",
        "EVALUATINGINTELL",
        "FENCINGG",
        "FENCINGL",
        "FISHINGG",
        "FISHINGL",
        "FOCUSG",
        "FOCUSL",
        "FORENSICSG",
        "FORENSICSL",
        "HEALINGG",
        "HEALINGL",
        "HERDINGG",
        "HERDINGL",
        "HIDINGG",
        "HIDINGL",
        "INSCRIPTIONG",
        "INSCRIPTIONL",
        "ITEMIDG",
        "ITEMIDL",
        "LOCKPICKINGG",
        "LOCKPICKINGL",
        "LUMBERJACKINGG",
        "LUMBERJACKINGL",
        "MACEFIGHTINGG",
        "MACEFIGHTINGL",
        "MAGERYG",
        "MAGERYL",
        "MAGICRESISTANCEG",
        "MAGICRESISTANCEL",
        "MEDITATIONG",
        "MEDITATIONL",
        "MININGG",
        "MININGL",
        "MUSICIANSHIPG",
        "MUSICIANSHIPL",
        "PARRYINGG",
        "PARRYINGL",
        "PEACEMAKINGG",
        "PEACEMAKINGL",
        "POISONINGG",
        "POISONINGL",
        "PROVOCATIONG",
        "PROVOCATIONL",
        "REMOVETRAPG",
        "REMOVETRAPL",
        "SNOOPINGG",
        "SNOOPINGL",
        "SPIRITSPEAKG",
        "SPIRITSPEAKL",
        "STEALINGG",
        "STEALINGL",
        "STEALTHG",
        "STEALTHL",
        "SWORDSMANSHIPG",
        "SWORDSMANSHIPL",
        "TACTICSG",
        "TACTICSL",
        "TAILORINGG",
        "TAILORINGL",
        "TAMINGG",
        "TAMINGL",
        "TASTEIDG",
        "TASTEIDL",
        "TINKERINGG",
        "TINKERINGL",
        "TRACKINGG",
        "TRACKINGL",
        "VETERINARYG",
        "VETERINARYL",
        "WRESTLINGG",
        "WRESTLINGL"
    };

    public static readonly Dictionary<string, string> GeneralTagDescriptions = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        { "GET", "Copies properties from a base DFN section." },
        { "NAME", "Display name of the item, NPC, or object." },
        { "NAME2", "Secondary name used by some DFN systems." },
        { "ID", "Graphic or object ID in hexadecimal." },
        { "TYPE", "UOX3 object type value that controls behavior." },
        { "SCRIPT", "Script trigger or JS script ID attached to the object." },
        { "COLOUR", "Hue or colour value, usually in hexadecimal." },
        { "COLOR", "Hue or color value, usually in hexadecimal." },
        { "AMOUNT", "Stack or quantity amount." },
        { "WEIGHT", "Base weight of the object." },
        { "WEIGHTMAX", "Maximum carry weight for containers." },
        { "VALUE", "Buy or sell value." },
        { "MOVABLE", "Controls whether the object can be moved." },
        { "DECAY", "Controls whether the object decays over time." },
        { "GOOD", "Vendor good category." },
        { "RESTOCK", "Amount restocked by vendors." },
        { "LAYER", "Equipment layer used by worn items." },
        { "MORE", "Generic extra data field." },
        { "MOREX", "Generic extra data X field." },
        { "MOREY", "Generic extra data Y field." },
        { "MOREZ", "Generic extra data Z field." },
        { "HP", "Hit points or durability range/value." },
        { "STR", "Strength stat or range." },
        { "DEX", "Dexterity stat or range." },
        { "INT", "Intelligence stat or range." },
        { "MANA", "Mana value or range." },
        { "STAMINA", "Stamina value or range." },
        { "FAME", "Fame value." },
        { "KARMA", "Karma value." },
        { "ATT", "Attack value." },
        { "DEF", "Defense value." },
        { "ARMOR", "Armor rating." },
        { "DAMAGE", "Damage value or range." },
        { "RACE", "Race assigned to an NPC or character." },
        { "TITLE", "Title text shown on the object or NPC." },
        { "NPCAI", "NPC AI type." },
        { "NPCWANDER", "NPC wandering behavior." },
        { "FLAG", "Object or NPC flag setting." },
        { "NPC", "Direct NPC section reference." },
        { "NPCLIST", "NPC list section reference." },
        { "ITEM", "Direct item section reference." },
        { "ITEMLIST", "Item list section reference." },
        { "PACKITEM", "Item added to backpack or container on creation." },
        { "EQUIPITEM", "Item equipped on creation." },
        { "COLORLIST", "Random hue list reference." },
        { "LOOT", "Direct loot section reference." },
        { "LOOTLIST", "Loot list section reference." },
        { "RESOURCE", "Crafting resource requirement." },
        { "SKILL", "Crafting or skill requirement." },
        { "MINRANK", "Minimum crafting rank required." },
        { "MAXRANK", "Maximum crafting rank allowed." },
        { "ADDITEM", "Crafted or created result item." },
        { "MENU", "Crafting menu category number." },
        { "SUBMENU", "Crafting submenu category number." },
        { "SOUND", "Sound effect ID." },
        { "SFX", "Sound effect ID." },
        { "ANIM", "Animation ID or action." },
        { "RESIST", "Resistance-related value." },
        { "MAGICRESISTANCE", "Magic resistance skill value or range." },
        { "PARRYING", "Parrying skill value or range." },
        { "SWORDSMANSHIP", "Swordsmanship skill value or range." },
        { "FENCING", "Fencing skill value or range." },
        { "MACEFIGHTING", "Macefighting skill value or range." },
        { "TACTICS", "Tactics skill value or range." },
        { "WRESTLING", "Wrestling skill value or range." },
        { "ARCHERY", "Archery skill value or range." },
        { "MAGERY", "Magery skill value or range." },
        { "MEDITATION", "Meditation skill value or range." },
        { "HEALING", "Healing skill value or range." },
        { "ANATOMY", "Anatomy skill value or range." },
        { "MINING", "Mining skill value or range." },
        { "LUMBERJACKING", "Lumberjacking skill value or range." },
        { "HIDING", "Hiding skill value or range." },
        { "STEALTH", "Stealth skill value or range." },
        { "SNOOPING", "Snooping skill value or range." },
        { "STEALING", "Stealing skill value or range." },
        { "LOCKPICKING", "Lockpicking skill value or range." },
        { "ITEMID", "Item identification skill value or range." },
        { "ARMSLORE", "Arms lore skill value or range." },
        { "TASTEID", "Taste identification skill value or range." },
        { "COOKING", "Cooking skill value or range." },
        { "FISHING", "Fishing skill value or range." },
        { "CAMPING", "Camping skill value or range." },
        { "TRACKING", "Tracking skill value or range." },
        { "HERDING", "Herding skill value or range." },
        { "BEGGING", "Begging skill value or range." },
        { "POISONING", "Poisoning skill value or range." },
        { "CARTOGRAPHY", "Cartography skill value or range." },
        { "ORIGIN", "Custom source marker for where a section came from." },
        { "CUSTOMINTTAG", "Custom integer tag stored on the object." }
    };

    public static readonly Dictionary<string, string> CreatureTagDescriptions = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        { "ANTIBLINK", "Legacy tag, originally used to identify creatures that lacked certain attack animations, now no longer used for anything." },
        { "ANIMAL", "Identifies creature as an animal." },
        { "ANIM_ATTACK1", "First attack animation with frame count. Creatures randomize between all defined attack animations in combat." },
        { "ANIM_ATTACK2", "Second attack animation with frame count. Creatures randomize between all defined attack animations in combat." },
        { "ANIM_ATTACK3", "Third attack animation with frame count. Creatures randomize between all defined attack animations in combat." },
        { "ANIM_CASTAREA", "Area-based spellcasting animation with frame count." },
        { "ANIM_CASTTARGET", "Target-based spellcasting animation with frame count." },
        { "ANIM_CAST3", "Third spellcasting animation. Currently unused." },
        { "FLIES", "Identifies creature as one that can fly." },
        { "HUMAN", "Identifies creature as a human or one with human-like properties." },
        { "ICON", "ID of icon or art used to represent creature in Tracking menus." },
        { "MOVEMENT", "Defines how creature moves in the world: LAND, WATER, or BOTH." },
        { "MOUNTID", "Mount ID associated with creature. Without this, creature is not mountable." },
        { "PACKANIMAL", "Identifies creature as a pack animal." },
        { "SOUND_IDLE", "Sound that plays randomly while creature is idle." },
        { "SOUND_STARTATTACK", "Sound that plays when creature initiates combat." },
        { "SOUND_ATTACK", "Sound that plays when creature hits a target in combat." },
        { "SOUND_DEFEND", "Sound that plays when target is hit in combat." },
        { "SOUND_DIE", "Sound that plays when creature dies." }
    };

    public static readonly Dictionary<string, string> CreateTagDescriptions = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        { "MENU", "Tag in crafting menu system that points to a menuentry section in crafting DFNs." },
        { "SUBMENU", "Tag in crafting menu system that points to a submenu section in crafting DFNs." },
        { "ITEM", "Tag in crafting menu system that points to an item section in crafting DFNs." },
        { "NAME", "Label shown in the crafting menu. Not necessarily the actual final item name." },
        { "ID", "Artwork ID displayed in the crafting menu for a given item." },
        { "COLOUR", "Colour associated with item. Unused by hard-coded crafting system, but may be used by scripts." },
        { "COLOR", "Color associated with item. Unused by hard-coded crafting system, but may be used by scripts." },
        { "RESOURCE", "Required crafting resource, with optional amount and colour values." },
        { "SKILL", "Required skill ID plus minimum and maximum skill-point values." },
        { "ADDITEM", "Section header name of the actual item that will be crafted, from item DFNs." },
        { "MINRANK", "Minimum item rank that can be randomly applied by the rank system." },
        { "MAXRANK", "Maximum item rank that can be randomly applied by the rank system." },
        { "SOUND", "Sound effect played when the item is crafted." },
        { "DELAY", "Delay in milliseconds before crafting completes." },
        { "SPELL", "Spell ID required to be present in a spellbook in order to craft the item." }
    };

    public static readonly Dictionary<string, string> NpcTagDescriptions = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        { "ALCHEMY", "Set Alchemy skill." },
        { "ANATOMY", "Set Anatomy skill." },
        { "ANIMALLORE", "Set Animal Lore skill." },
        { "ARCHERY", "Set Archery skill." },
        { "ARMSLORE", "Set Arms Lore skill." },
        { "AWAKE", "Marks the NPC as permanently awake." },
        { "BACKPACK", "If tag is present, add backpack to NPC." },
        { "BEGGING", "Set Begging skill." },
        { "BLACKSMITHING", "Set Blacksmithing skill." },
        { "BOWCRAFT", "Set Bowcraft or Fletching skill." },
        { "BUSHIDO", "Set Bushido skill." },
        { "CAMPING", "Set Camping skill." },
        { "CARPENTRY", "Set Carpentry skill." },
        { "CARTOGRAPHY", "Set Cartography skill." },
        { "CARVE", "Set carve list section to use for butchered corpses." },
        { "CHIVALRY", "Set Chivalry skill." },
        { "COLOR", "Set NPC color by hex or decimal value." },
        { "COLOUR", "Set NPC colour by hex or decimal value." },
        { "COLORLIST", "Set random color from colors.dfn." },
        { "COLOURLIST", "Set random colour from colors.dfn." },
        { "COLORMATCHHAIR", "Match beard color to hair color." },
        { "COLOURMATCHHAIR", "Match beard colour to hair colour." },
        { "COOKING", "Set Cooking skill." },
        { "CUSTOMINTTAG", "Adds custom JS int tag to character." },
        { "CUSTOMSTRINGTAG", "Adds custom JS string tag to character." },
        { "DAMAGE", "Set damage or attack values." },
        { "ATT", "Set damage or attack values." },
        { "DEF", "Set defense or physical resist value." },
        { "DEFBONUS", "Set defense bonus applied on top of standard DEF." },
        { "DETECTINGHIDDEN", "Set Detecting Hidden skill." },
        { "DEX", "Set Dexterity stat." },
        { "DIR", "Set default direction on spawn." },
        { "DIRECTION", "Set default direction on spawn." },
        { "ELEMENTRESIST", "Set elemental resist values." },
        { "ERBONUS", "Set elemental resistance bonus." },
        { "EMOTECOLOUR", "Set default emote text colour." },
        { "EMOTECOLOR", "Set default emote text color." },
        { "ENTICEMENT", "Set Enticement skill." },
        { "EQUIPITEM", "Equip item from item DFNs." },
        { "EVALUATINGINTEL", "Set Evaluating Intelligence skill." },
        { "FAME", "Set fame value." },
        { "FENCING", "Set Fencing skill." },
        { "FISHING", "Set Fishing skill." },
        { "FLAG", "Set NPC flag: neutral, innocent, or evil." },
        { "FLEEAT", "Set health percentage where NPC starts fleeing." },
        { "FLEEINGSPEED", "Set fleeing speed." },
        { "FLEEINGSPEEDMOUNTED", "Set fleeing speed while mounted." },
        { "FOCUS", "Set Focus skill." },
        { "FOOD", "Set food list from foodlists.dfn." },
        { "FORENSICS", "Set Forensics skill." },
        { "FX1", "Coordinate used with NPC wander modes." },
        { "FX2", "Coordinate used with NPC wander modes." },
        { "FY1", "Coordinate used with NPC wander modes." },
        { "FY2", "Coordinate used with NPC wander modes." },
        { "FZ1", "Coordinate used with NPC wander modes." },
        { "GET", "Inherit properties from another NPC section." },
        { "GETUO", "Era-based inheritance from another NPC section." },
        { "GETT2A", "Era-based inheritance from another NPC section." },
        { "GETTD", "Era-based inheritance from another NPC section." },
        { "GETUOR", "Era-based inheritance from another NPC section." },
        { "GETLBR", "Era-based inheritance from another NPC section." },
        { "GETAOS", "Era-based inheritance from another NPC section." },
        { "GETSE", "Era-based inheritance from another NPC section." },
        { "GETML", "Era-based inheritance from another NPC section." },
        { "GETSA", "Era-based inheritance from another NPC section." },
        { "GETHS", "Era-based inheritance from another NPC section." },
        { "GETTOL", "Era-based inheritance from another NPC section." },
        { "GOLD", "Set carried gold amount." },
        { "HAIRCOLOR", "Set NPC hair color." },
        { "HAIRCOLOUR", "Set NPC hair colour." },
        { "HEALING", "Set Healing skill." },
        { "HERDING", "Set Herding skill." },
        { "HIDAMAGE", "Set max damage value." },
        { "HIDING", "Set Hiding skill." },
        { "HP", "Set starting hitpoints." },
        { "HPMAX", "Set maximum hitpoints." },
        { "HEALTHREGENBONUS", "Increases the rate at which health regenerates over time while the item is equipped or applied." },
        { "STAMINAREGENBONUS", "Increases the rate at which stamina regenerates over time while the item is equipped or applied." },
        { "MANAREGENBONUS", "Increases the rate at which mana regenerates over time while the item is equipped or applied." },
        { "ID", "Set NPC body ID." },
        { "IMBUING", "Set Imbuing skill." },
        { "INSCRIPTION", "Set Inscription skill." },
        { "INTELLIGENCE", "Set Intelligence stat." },
        { "INT", "Set Intelligence stat." },
        { "ITEMID", "Set Item Identification skill." },
        { "KARMA", "Set karma value." },
        { "LOCKPICKING", "Set Lockpicking skill." },
        { "LODAMAGE", "Set minimum damage value." },
        { "LOOT", "Adds random loot to a container from lootlists.dfn. Double-click this row in Section tags to pick a lootlist and optional amount." },
        { "LUMBERJACKING", "Set Lumberjacking skill." },
        { "MACEFIGHTING", "Set Macefighting skill." },
        { "MAGERY", "Set Magery skill." },
        { "MAGICRESISTANCE", "Set Magic Resistance skill." },
        { "MANA", "Set starting mana." },
        { "MANAMAX", "Set maximum mana." },
        { "MEDITATION", "Set Meditation skill." },
        { "MINING", "Set Mining skill." },
        { "MUSICIANSHIP", "Set Musicianship skill." },
        { "MYSTICISM", "Set Mysticism skill." },
        { "NAME", "Set NPC name." },
        { "NAMELIST", "Set random NPC name from namelists.dfn." },
        { "NECROMANCY", "Set Necromancy skill." },
        { "NINJITSU", "Set Ninjitsu skill." },
        { "NOTRAIN", "NPC will not train players." },
        { "NPCAI", "Set NPC AI type." },
        { "NPCWANDER", "Set NPC wander mode." },
        { "ORIGIN", "Store which expansion or era the NPC originated in." },
        { "PACKITEM", "Add item to NPC backpack." },
        { "PARRYING", "Set Parrying skill." },
        { "PEACEMAKING", "Set Peacemaking skill." },
        { "POISONING", "Set Poisoning skill." },
        { "POISONSTRENGTH", "Set poison strength for NPC." },
        { "PRIV", "Set NPC privileges. Currently not working." },
        { "PROVOCATION", "Set Provocation skill." },
        { "RACE", "Set race ID from races.dfn." },
        { "REATTACKAT", "Set health percentage where NPC returns to combat." },
        { "REMOVETRAP", "Set Remove Trap skill." },
        { "RSHOPITEM", "NPC will purchase item defined here." },
        { "RUNNINGSPEED", "Set NPC running speed." },
        { "RUNNINGSPEEDMOUNTED", "Set NPC mounted running speed." },
        { "RUNS", "NPC uses running animations and running speed in combat." },
        { "SAYCOLOR", "Set NPC speech color." },
        { "SAYCOLOUR", "Set NPC speech colour." },
        { "SCRIPT", "Attach JS script ID on creation." },
        { "SECTIONID", "Override stored section ID." },
        { "SELLITEM", "NPC will sell item defined here." },
        { "SHOPITEM", "NPC will have item added to already-bought-items pack." },
        { "SHOPKEEPER", "Turn NPC into a shopkeeper on creation." },
        { "SHOPLIST", "Shoplist reference. Not currently used." },
        { "SKILL", "Set a specific skill by skill number and value." },
        { "SKIN", "Set skin color." },
        { "SKINLIST", "Set random skin color from colors.dfn." },
        { "SNOOPING", "Set Snooping skill." },
        { "SPADELAY", "Set minimum delay between spell casts." },
        { "SPATTACK", "Set spell circles the NPC can use." },
        { "SPELLWEAVING", "Set Spellweaving skill." },
        { "SPIRITSPEAK", "Set Spirit Speak skill." },
        { "SPLIT", "NPC splits into two when hit, if script support is attached." },
        { "SPLITCHANCE", "Chance for NPC to split when hit." },
        { "STAMINA", "Set starting stamina." },
        { "STAMINAMAX", "Set maximum stamina." },
        { "STEALING", "Set Stealing skill." },
        { "STEALTH", "Set Stealth skill." },
        { "STRENGTH", "Set Strength stat." },
        { "STR", "Set Strength stat." },
        { "SWORDSMANSHIP", "Set Swordsmanship skill." },
        { "TACTICS", "Set Tactics skill." },
        { "TAILORING", "Set Tailoring skill." },
        { "TAMEDHUNGER", "Set hunger rate and chance to go wild." },
        { "TAMING", "Set Animal Taming skill." },
        { "TASTEID", "Set Taste Identification skill." },
        { "THROWING", "Set Throwing skill." },
        { "TINKERING", "Set Tinkering skill." },
        { "TITLE", "Set NPC title." },
        { "TOPEACE", "Set minimum skill to use peacemaking against this NPC." },
        { "TOPROV", "Set minimum skill to use provocation against this NPC." },
        { "TOTAME", "Set minimum skill to tame this NPC." },
        { "TRACKING", "Set Tracking skill." },
        { "VETERINARY", "Set Veterinary skill." },
        { "WALKINGSPEED", "Set NPC walking speed." },
        { "WALKINGSPEEDMOUNTED", "Set NPC mounted walking speed." },
        { "WILLHUNGER", "If 1, NPC is affected by hunger, and will never need food." },
        { "WRESTLING", "Set Wrestling skill." }
    };

    public static readonly Dictionary<string, string> ItemTagDescriptions = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        { "AC", "Set armour class of item." },
        { "ADDMENUITEM", "Automatically add item to add-menu when menu is generated." },
        { "ARTIFACTRARITY", "Indicates the rarity level of an artifact item." },
        { "AMMO", "Used with ranged weapons to specify required ammo." },
        { "AMMOFX", "Used with ranged weapons to specify missile FX." },
        { "AMOUNT", "Set fixed or random amount of items." },
        { "ATT", "Set minimum and maximum weapon damage." },
        { "BASEWEIGHT", "Set base weight of item before contents." },
        { "COLD", "Marks weapon as cold elemental damage." },
        { "COLOR", "Set item color in hex or decimal. Double-click this row in Section tags to pick a hue from hues.mul." },
        { "COLOUR", "Set item colour in hex or decimal. Double-click this row in Section tags to pick a hue from hues.mul." },
        { "COLORLIST", "Set random color from colors.dfn." },
        { "COLOURLIST", "Set random colour from colors.dfn." },
        { "CORPSE", "Define item as a corpse." },
        { "CREATOR", "Serial of character that created item." },
        { "CUSTOMINTTAG", "Adds custom JS int tag to item." },
        { "CUSTOMSTRINGTAG", "Adds custom JS string tag to item." },
        { "DURABILITYHPBONUS", "Increase item durability by percentage." },
        { "DAMAGE", "Set minimum and maximum weapon damage." },
        { "DAMAGEABLE", "Allows client to display healthbar for object." },
        { "DAMAGEINCREASE", "Increase base weapon damage by percentage." },
        { "DECAY", "Controls whether item decays." },
        { "DEF", "Set physical resist or armor value." },
        { "DEFBONUS", "Set defense bonus applied on top of DEF." },
        { "DEFENSECHANCE", "Increase chance to avoid incoming physical attacks." },
        { "DEX", "Minimum dexterity required to equip item." },
        { "DEXADD", "Temporary dexterity bonus while equipped." },
        { "DIR", "Direction value, often used for light pattern or radius." },
        { "DISABLED", "If 1, item is disabled." },
        { "DISPELLABLE", "Marks item as dispellable." },
        { "DYE", "Marks item as dyeable." },
        { "EVENT", "Associate item with a custom server event." },
        { "ELEMENTRESIST", "Set fire, cold, energy and poison resist values." },
        { "ERBONUS", "Set elemental resistance bonus." },
        { "GET", "Inherit properties from another item section." },
        { "GETUO", "Era-based inheritance from another item section." },
        { "GETT2A", "Era-based inheritance from another item section." },
        { "GETTD", "Era-based inheritance from another item section." },
        { "GETUOR", "Era-based inheritance from another item section." },
        { "GETLBR", "Era-based inheritance from another item section." },
        { "GETAOS", "Era-based inheritance from another item section." },
        { "GETSE", "Era-based inheritance from another item section." },
        { "GETML", "Era-based inheritance from another item section." },
        { "GETSA", "Era-based inheritance from another item section." },
        { "GETHS", "Era-based inheritance from another item section." },
        { "GETTOL", "Era-based inheritance from another item section." },
        { "GUMPTYPE", "Overrides the container gump used when opening this container, and can optionally define custom random placement bounds for items placed inside it via PlaceInPack()." },
        { "GLOW", "Attach a hidden lightsource to make item glow." },
        { "GLOWBC", "Set glow effect color." },
        { "GLOWTYPE", "Set glow effect type." },
        { "GOOD", "Category of goods used for the Advanced Trade System." },
        { "HEAT", "Marks weapon as heat elemental damage." },
        { "HEALTHLEECH", "Chance to convert damage dealt into health." },
        { "HEALTHBONUS", "Direct increase to maximum health." },
        { "HIDAMAGE", "Set maximum weapon damage." },
        { "HITCHANCE", "Increase chance to land a physical attack." },
        { "HP", "Set item hitpoints." },
        { "HEALTHREGENBONUS", "Increases the rate at which health regenerates over time while the item is equipped or applied." },
        { "STAMINAREGENBONUS", "Increases the rate at which stamina regenerates over time while the item is equipped or applied." },
        { "MANAREGENBONUS", "Increases the rate at which mana regenerates over time while the item is equipped or applied." },
        { "ID", "Set tile ID of item art. In the items folder, double-click the ID row in Section tags to pick from artLegacyMUL.uop using tiledata.mul names." },
        { "INTADD", "Temporary intelligence bonus while equipped." },
        { "INTELLIGENCE", "Minimum intelligence required to equip item." },
        { "INTERVAL", "Spawner interval in minutes." },
        { "LAYER", "Define equip layer for equippable item. In the items folder, double-click the LAYER row in Section tags to pick from known UOX3 item layers." },
        { "LIGHT", "Marks weapon as light elemental damage." },
        { "LIGHTNING", "Marks weapon as lightning elemental damage." },
        { "LODAMAGE", "Set minimum weapon damage." },
        { "LOOT", "Adds random loot to a container from lootlists.dfn." },
        { "LOWERSTATREQ", "Reduce stat requirements needed to equip or use item." },
        { "LUCK", "Adds luck value." },
        { "MANALEECH", "Chance to convert damage dealt into mana." },
        { "MANABONUS", "Direct increase to maximum mana." },
        { "MAXHP", "Set maximum hitpoints or durability." },
        { "MAXITEMS", "Maximum number of items a container can hold." },
        { "MAXRANGE", "Maximum range of item." },
        { "MAXUSES", "Set item's max uses." },
        { "MORE", "Generic variable whose purpose depends on context." },
        { "MORE0", "Generic variable whose purpose depends on context." },
        { "MORE1", "Generic variable whose purpose depends on context." },
        { "MORE2", "Generic variable whose purpose depends on context." },
        { "MOREX", "Generic comma-separated morex, morey, morez values." },
        { "MOREY", "Generic comma-separated morex, morey, morez values." },
        { "MOREZ", "Generic comma-separated morex, morey, morez values." },
        { "MOREXYZ", "Generic comma-separated morex, morey, morez values." },
        { "MOVABLE", "Set movable status of item." },
        { "NAME", "Set item name." },
        { "NAMELIST", "Set random item name from namelists.dfn." },
        { "NAME2", "Secondary hidden name of item." },
        { "NEWBIE", "Marks item as blessed or newbie." },
        { "OFFSPELL", "Legacy property not currently used." },
        { "ORIGIN", "Store which expansion or era item originated in." },
        { "PACKITEM", "Add specified item to container." },
        { "PILEABLE", "Marks item as pileable or stackable." },
        { "POISONDAMAGE", "Marks weapon as poison elemental damage." },
        { "POISONED", "Set poison strength on item." },
        { "PRIV", "Set item priv value." },
        { "RACE", "Set race that weapon deals double damage against." },
        { "RESISTFIRE", "Decrease damage from fire-based attacks." },
        { "RESISTCOLD", "Decrease damage from cold-based attacks." },
        { "RESISTLIGHTING", "Decrease damage from energy-based attacks." },
        { "RESISTPOISON", "Decrease damage from poison-based attacks." },
        { "RAIN", "Marks weapon as rain elemental damage." },
        { "RANK", "Used by crafting system to determine quality." },
        { "RESTOCK", "Amount shopkeepers restock." },
        { "SCRIPT", "Attach JS script ID on item creation." },
        { "SECTIONID", "Override stored section ID." },
        { "SK_MADE", "Defines skill used to create the item." },
        { "SNOW", "Marks weapon as snow elemental damage." },
        { "SPAWNOBJ", "Spawner object target item or NPC section." },
        { "SPAWNOBJLIST", "Spawner object list target from itemlists or npclists." },
        { "SPD", "Set weapon attack speed." },
        { "SWINGSPEEDINCREASE", "Increase base weapon swing speed by percentage." },
        { "STEALABLE", "Determines under which conditions item can be stolen." },
        { "STAMINALEECH", "Chance to convert damage dealt into stamina." },
        { "STAMINABONUS", "Direct increase to maximum stamina." },
        { "SPELLS", "Define which spells a new spellbook starts with." },
        { "STRADD", "Temporary strength bonus while equipped." },
        { "STRENGTH", "Set strength requirement for equipping item." },
        { "STR", "Set strength requirement for equipping item." },
        { "TYPE", "Set item type. In the items folder, double-click the TYPE row in Section tags to pick from known UOX3 item types." },
        { "USESLEFT", "Set remaining uses." },
        { "VALUE", "Set buy value and sell value." },
        { "VISIBLE", "Set visibility of item." },
        { "WEIGHT", "Set item weight." },
        { "WEIGHTMAX", "Set container weight capacity." },
        { "WIPE", "Determines whether item is affected by item wipes." }
    };

    public static readonly Dictionary<string, string> RaceTagDescriptions = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        { "ALLOWEQUIPLIST", "Members of the race can equip items listed in the specified EQUIPLIST section." },
        { "ALLSKILLSG", "Bonus applied to all skill checks based on the specified combat mod ID." },
        { "ALLSKILLSL", "Penalty applied to all skill checks based on the specified combat mod ID." },
        { "ARMORREST", "Sets the armor class restriction of the race." },
        { "BANEQUIPLIST", "Members of the race are forbidden from equipping items listed in the specified EQUIPLIST section." },
        { "BEARDMIN", "Minimum beard colour allowed for the race." },
        { "BEARDMAX", "Maximum beard colour allowed for the race." },
        { "BLOODCOLOUR", "Sets the blood colour used for members of the race." },
        { "COLDAFFECT", "If present, race is affected by cold." },
        { "COLDLEVEL", "Cold level where members of the race start taking damage." },
        { "COLDDAMAGE", "Maximum damage caused by cold before resistances." },
        { "COLDSECS", "How often cold damage can occur, in seconds." },
        { "DEXCAP", "Cap on Dexterity stat for the race." },
        { "GENDER", "Restrict membership in race to MALE or FEMALE." },
        { "HAIRMIN", "Minimum hair colour allowed for the race." },
        { "HAIRMAX", "Maximum hair colour allowed for the race." },
        { "HEATAFFECT", "If present, race is affected by heat." },
        { "HEATDAMAGE", "Maximum damage caused by heat before resistances." },
        { "HEATLEVEL", "Heat level where members of the race start taking damage." },
        { "HEATSECS", "How often heat damage can occur, in seconds." },
        { "HPMOD", "Adjusts maximum hitpoints by a percentage of Strength." },
        { "HUNGER", "Time between hunger checks and damage taken when starving." },
        { "INTCAP", "Cap on Intelligence stat for the race." },
        { "LIGHTAFFECT", "If present, race is affected by light." },
        { "LIGHTDAMAGE", "Base amount of damage caused by light." },
        { "LIGHTLEVEL", "Light level threshold used for light-based damage checks." },
        { "LIGHTSECS", "How often light damage is applied in seconds." },
        { "LIGHTNINGAFFECT", "If present, race is affected by lightning." },
        { "LIGHTNINGDAMAGE", "Maximum damage caused by lightning before resistances." },
        { "LIGHTNINGCHANCE", "Chance to get hit by lightning during a storm." },
        { "LANGUAGEMIN", "Minimum Spirit Speak skill needed for outsiders to understand this race." },
        { "MAGICRESISTANCE", "Magic resistance bonus for members of the race." },
        { "MANAMOD", "Adjusts maximum mana by a percentage of Intelligence." },
        { "MAXWEIGHTBONUS", "Bonus to max weight capacity for members of the race." },
        { "NAME", "Name of the race." },
        { "NOBEARD", "If present, race members cannot have beards." },
        { "NIGHTVIS", "Light level at which night vision kicks in for this race." },
        { "PLAYERRACE", "Indicates whether race is intended for players." },
        { "POISONRESISTANCE", "Poison resistance bonus for members of the race." },
        { "PARENTRACE", "Parent race ID from which this race inherits properties." },
        { "REQUIREBEARD", "If present, members of the race are required to have facial hair." },
        { "RAINAFFECT", "If present, race is affected by rain." },
        { "RAINDAMAGE", "Maximum damage caused by rain before resistances." },
        { "RAINSECS", "How often rain damage is applied in seconds." },
        { "RACERELATION", "Defines race relation toward another race." },
        { "RACIALENEMY", "Marks another race as an enemy." },
        { "RACIALAID", "Marks another race as an ally." },
        { "SKINMIN", "Minimum skin colour allowed for the race." },
        { "SKINMAX", "Maximum skin colour allowed for the race." },
        { "SNOWAFFECT", "If present, race is affected by snow." },
        { "SNOWDAMAGE", "Maximum damage caused by snow before resistances." },
        { "SNOWSECS", "How often snow damage can occur, in seconds." },
        { "STAMMOD", "Adjusts maximum stamina by a percentage of Dexterity." },
        { "STORMAFFECT", "If present, race is affected by storms." },
        { "STORMDAMAGE", "Maximum damage caused by storms before resistances." },
        { "STORMSECS", "How often storm damage can occur, in seconds." },
        { "STRCAP", "Cap on Strength stat for the race." },
        { "THIRST", "Time between thirst checks and damage taken when extremely thirsty." },
        { "VISRANGE", "Default visibility range of the race." },
        { "ALCHEMYG", "Bonus applied to Alchemy skill checks." },
        { "ALCHEMYL", "Penalty applied to Alchemy skill checks." },
        { "ANATOMYG", "Bonus applied to Anatomy skill checks." },
        { "ANATOMYL", "Penalty applied to Anatomy skill checks." },
        { "ANIMALLOREG", "Bonus applied to Animal Lore skill checks." },
        { "ANIMALLOREL", "Penalty applied to Animal Lore skill checks." },
        { "ARCHERYG", "Bonus applied to Archery skill checks." },
        { "ARCHERYL", "Penalty applied to Archery skill checks." },
        { "ARMSLOREG", "Bonus applied to Arms Lore skill checks." },
        { "ARMSLOREL", "Penalty applied to Arms Lore skill checks." },
        { "BEGGINGG", "Bonus applied to Begging skill checks." },
        { "BEGGINGL", "Penalty applied to Begging skill checks." },
        { "BLACKSMITHINGG", "Bonus applied to Blacksmithing skill checks." },
        { "BLACKSMITHINGL", "Penalty applied to Blacksmithing skill checks." },
        { "BOWCRAFTG", "Bonus applied to Bowcraft skill checks." },
        { "BOWCRAFTL", "Penalty applied to Bowcraft skill checks." },
        { "BUSHIDOG", "Bonus applied to Bushido skill checks." },
        { "BUSHIDOL", "Penalty applied to Bushido skill checks." },
        { "CAMPINGG", "Bonus applied to Camping skill checks." },
        { "CAMPINGL", "Penalty applied to Camping skill checks." },
        { "CARPENTRYG", "Bonus applied to Carpentry skill checks." },
        { "CARPENTRYL", "Penalty applied to Carpentry skill checks." },
        { "CARTOGRAPHYG", "Bonus applied to Cartography skill checks." },
        { "CARTOGRAPHYL", "Penalty applied to Cartography skill checks." },
        { "CHIVALRYG", "Bonus applied to Chivalry skill checks." },
        { "CHIVALRYL", "Penalty applied to Chivalry skill checks." },
        { "COOKINGG", "Bonus applied to Cooking skill checks." },
        { "COOKINGL", "Penalty applied to Cooking skill checks." },
        { "DETECTINGHIDDENG", "Bonus applied to Detecting Hidden skill checks." },
        { "DETECTINGHIDDENL", "Penalty applied to Detecting Hidden skill checks." },
        { "DISCORDANCEG", "Bonus applied to Discordance skill checks." },
        { "DISCORDANCEL", "Penalty applied to Discordance skill checks." },
        { "ENTICEMENTG", "Bonus applied to Enticement skill checks." },
        { "ENTICEMENTL", "Penalty applied to Enticement skill checks." },
        { "EVALUATINGINTELG", "Bonus applied to Evaluating Intelligence skill checks." },
        { "EVALUATINGINTELL", "Penalty applied to Evaluating Intelligence skill checks." },
        { "FENCINGG", "Bonus applied to Fencing skill checks." },
        { "FENCINGL", "Penalty applied to Fencing skill checks." },
        { "FISHINGG", "Bonus applied to Fishing skill checks." },
        { "FISHINGL", "Penalty applied to Fishing skill checks." },
        { "FOCUSG", "Bonus applied to Focus skill checks." },
        { "FOCUSL", "Penalty applied to Focus skill checks." },
        { "FORENSICSG", "Bonus applied to Forensics skill checks." },
        { "FORENSICSL", "Penalty applied to Forensics skill checks." },
        { "HEALINGG", "Bonus applied to Healing skill checks." },
        { "HEALINGL", "Penalty applied to Healing skill checks." },
        { "HERDINGG", "Bonus applied to Herding skill checks." },
        { "HERDINGL", "Penalty applied to Herding skill checks." },
        { "HIDINGG", "Bonus applied to Hiding skill checks." },
        { "HIDINGL", "Penalty applied to Hiding skill checks." },
        { "INSCRIPTIONG", "Bonus applied to Inscription skill checks." },
        { "INSCRIPTIONL", "Penalty applied to Inscription skill checks." },
        { "ITEMIDG", "Bonus applied to Item Identification skill checks." },
        { "ITEMIDL", "Penalty applied to Item Identification skill checks." },
        { "LOCKPICKINGG", "Bonus applied to Lockpicking skill checks." },
        { "LOCKPICKINGL", "Penalty applied to Lockpicking skill checks." },
        { "LUMBERJACKINGG", "Bonus applied to Lumberjacking skill checks." },
        { "LUMBERJACKINGL", "Penalty applied to Lumberjacking skill checks." },
        { "MACEFIGHTINGG", "Bonus applied to Macefighting skill checks." },
        { "MACEFIGHTINGL", "Penalty applied to Macefighting skill checks." },
        { "MAGERYG", "Bonus applied to Magery skill checks." },
        { "MAGERYL", "Penalty applied to Magery skill checks." },
        { "MAGICRESISTANCEG", "Bonus applied to Magic Resistance skill checks." },
        { "MAGICRESISTANCEL", "Penalty applied to Magic Resistance skill checks." },
        { "MEDITATIONG", "Bonus applied to Meditation skill checks." },
        { "MEDITATIONL", "Penalty applied to Meditation skill checks." },
        { "MININGG", "Bonus applied to Mining skill checks." },
        { "MININGL", "Penalty applied to Mining skill checks." },
        { "MUSICIANSHIPG", "Bonus applied to Musicianship skill checks." },
        { "MUSICIANSHIPL", "Penalty applied to Musicianship skill checks." },
        { "PARRYINGG", "Bonus applied to Parrying skill checks." },
        { "PARRYINGL", "Penalty applied to Parrying skill checks." },
        { "PEACEMAKINGG", "Bonus applied to Peacemaking skill checks." },
        { "PEACEMAKINGL", "Penalty applied to Peacemaking skill checks." },
        { "POISONINGG", "Bonus applied to Poisoning skill checks." },
        { "POISONINGL", "Penalty applied to Poisoning skill checks." },
        { "PROVOCATIONG", "Bonus applied to Provocation skill checks." },
        { "PROVOCATIONL", "Penalty applied to Provocation skill checks." },
        { "REMOVETRAPG", "Bonus applied to Remove Trap skill checks." },
        { "REMOVETRAPL", "Penalty applied to Remove Trap skill checks." },
        { "SNOOPINGG", "Bonus applied to Snooping skill checks." },
        { "SNOOPINGL", "Penalty applied to Snooping skill checks." },
        { "SPIRITSPEAKG", "Bonus applied to Spirit Speak skill checks." },
        { "SPIRITSPEAKL", "Penalty applied to Spirit Speak skill checks." },
        { "STEALINGG", "Bonus applied to Stealing skill checks." },
        { "STEALINGL", "Penalty applied to Stealing skill checks." },
        { "STEALTHG", "Bonus applied to Stealth skill checks." },
        { "STEALTHL", "Penalty applied to Stealth skill checks." },
        { "SWORDSMANSHIPG", "Bonus applied to Swordsmanship skill checks." },
        { "SWORDSMANSHIPL", "Penalty applied to Swordsmanship skill checks." },
        { "TACTICSG", "Bonus applied to Tactics skill checks." },
        { "TACTICSL", "Penalty applied to Tactics skill checks." },
        { "TAILORINGG", "Bonus applied to Tailoring skill checks." },
        { "TAILORINGL", "Penalty applied to Tailoring skill checks." },
        { "TAMINGG", "Bonus applied to Taming skill checks." },
        { "TAMINGL", "Penalty applied to Taming skill checks." },
        { "TASTEIDG", "Bonus applied to Taste Identification skill checks." },
        { "TASTEIDL", "Penalty applied to Taste Identification skill checks." },
        { "TINKERINGG", "Bonus applied to Tinkering skill checks." },
        { "TINKERINGL", "Penalty applied to Tinkering skill checks." },
        { "TRACKINGG", "Bonus applied to Tracking skill checks." },
        { "TRACKINGL", "Penalty applied to Tracking skill checks." },
        { "VETERINARYG", "Bonus applied to Veterinary skill checks." },
        { "VETERINARYL", "Penalty applied to Veterinary skill checks." },
        { "WRESTLINGG", "Bonus applied to Wrestling skill checks." },
        { "WRESTLINGL", "Penalty applied to Wrestling skill checks." }
    };

    public static HashSet<string> GetKnownTagsForFolderType(string folderType)
    {
        switch ((folderType ?? string.Empty).Trim().ToLowerInvariant())
        {
            case "creatures":
                return CreatureKnownDfnTags;
            case "create":
                return CreateKnownDfnTags;
            case "npc":
                return NpcKnownDfnTags;
            case "items":
                return ItemKnownDfnTags;
            case "race":
                return RaceKnownDfnTags;
            default:
                return GeneralKnownDfnTags;
        }
    }

    public static Dictionary<string, string> GetTagDescriptionsForFolderType(string folderType)
    {
        switch ((folderType ?? string.Empty).Trim().ToLowerInvariant())
        {
            case "creatures":
                return CreatureTagDescriptions;
            case "create":
                return CreateTagDescriptions;
            case "npc":
                return NpcTagDescriptions;
            case "items":
                return ItemTagDescriptions;
            case "race":
                return RaceTagDescriptions;
            default:
                return GeneralTagDescriptions;
        }
    }
}